- platform: rest
  resource: "http://<<IP>>/getdevdata.cgi?device=2&sn=<<SN>>"
  scan_interval: "00:01:00"
  name: "asw5000s"
  value_template: "{{ value_json.eto / 10 }}"
  json_attributes:
    - flg # ???
    - tim # date/time
    - tmp # inverter temperature / 10
    - fac # frequency / 100
    - pac # actual power watt
    - sac # apparent power
    - qac # reactive power
    - eto # total produced / 10
    - etd # total producted daily / 10
    - hto # running time
    - pf # ???
    - wan # ???
    - err # ???
    - vac # voltage / 10
    - iac # current / 10
    - vpv # string voltage
    - ipv # string current
    - str
