sensor:
  - name: "PVE Current production"
    unique_id: asw5000s_current_production
    state: "{{ state_attr('sensor.asw5000s', 'pac') | float }}"
    unit_of_measurement: "W"
    device_class: energy
    state_class: measurement

  - name: "PVE Daily production"
    unique_id: asw5000s_daily_production
    state: "{{ state_attr('sensor.asw5000s', 'etd') | float / 10 }}"
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - name: "PVE Total production"
    unique_id: asw5000s_total_production
    state: "{{ state_attr('sensor.asw5000s', 'eto') | float / 10 }}"
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - name: "PVE Inverter temperature"
    unique_id: asw5000s_temperature
    state: "{{ state_attr('sensor.asw5000s', 'tmp') | float / 10 }}"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
